version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: myapp

  backend:
    build:
      context: ./backend
    container_name: nest-backend
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/myapp
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3001:3000'
    depends_on:
      - backend

volumes:
  mongo-data:
